<?php

namespace VendorZone;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-04-19 at 15:47:52.
 */
class UserTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var User
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new User;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers namespace VendorZone\User::getIcon
     * @todo   Implement testGetIcon().
     */
    public function testGetIcon()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace VendorZone\User::getFirstContact
     * @todo   Implement testGetFirstContact().
     */
    public function testGetFirstContact()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace VendorZone\User::getDefaultContact
     * @todo   Implement testGetDefaultContact().
     */
    public function testGetDefaultContact()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace VendorZone\User::getId
     * @todo   Implement testGetId().
     */
    public function testGetId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace VendorZone\User::passwordChange
     * @todo   Implement testPasswordChange().
     */
    public function testPasswordChange()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace VendorZone\User::insertToMySQL
     * @todo   Implement testInsertToMySQL().
     */
    public function testInsertToMySQL()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace VendorZone\User::deleteButton
     * @todo   Implement testDeleteButton().
     */
    public function testDeleteButton()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace VendorZone\User::delete
     * @todo   Implement testDelete().
     */
    public function testDelete()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace VendorZone\User::getUserName
     * @todo   Implement testGetUserName().
     */
    public function testGetUserName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace VendorZone\User::getEmail
     * @todo   Implement testGetEmail().
     */
    public function testGetEmail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace VendorZone\User::getKeySelect
     * @todo   Implement testGetKeySelect().
     */
    public function testGetKeySelect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace VendorZone\User::getListingQuerySelect
     * @todo   Implement testGetListingQuerySelect().
     */
    public function testGetListingQuerySelect()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace VendorZone\User::htmlizeData
     * @todo   Implement testHtmlizeData().
     */
    public function testHtmlizeData()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers namespace VendorZone\User::operationsMenu
     * @todo   Implement testOperationsMenu().
     */
    public function testOperationsMenu()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}