#!/bin/bash
# postinst script for vendorzone

set -e
. /usr/share/debconf/confmodule

db_get "vendorzone/WEBUSER"
WEBUSER=${RET}

touch /etc/vendorzone/config.json

#Replace Key Value in Config File
function replace {
    cfg="/etc/vendorzone/config.php"
    sed -i "/${1}/c\define('${1}', '${2}');" $cfg
#    echo $cfg ${1} ${2}
}

replaceJSON() {
    cfg="/etc/vendorzone/config.json"
    sed -i "/${1}/c\        \"${1}\": \"${2}\"," $cfg
    echo $cfg ${1} ${2}
}


#Replace Key Value in PhinX Config File
function replaceYML {
    cfg="/var/lib/vendorzone/phinx.yml"
    sed -i "/${1}/c\        ${1}: ${2}" $cfg
#    echo $cfg ${1} ${2}
}

listOfConfigs="FLEXIBEE_URL
FLEXIBEE_LOGIN
FLEXIBEE_PASSWORD
FLEXIBEE_COMPANY
DB_TYPE
DB_HOST
DB_PORT
DB_USERNAME
DB_PASSWORD
DB_DATABASE"

IFS='                                                                                                                                                        
'                                                                                                                                                            
for keyword in $listOfConfigs                                                                                                                                
do                                                                                                                                                           
  db_get "vendorzone/$keyword"
  if [ "$RET" = "false" ]; then
    db_input critical "vendorzone/$keyword" || true
    db_go
    fi
# replace "$keyword" $RET
 replaceJSON "$keyword" $RET
done

if [ -x /usr/sbin/a2enconf ] ; then
    a2enconf vendorzone
fi

if [ -f /lib/systemd/system/apache2.service ] ; then
    systemctl reload apache2 3>/dev/null || true
fi

if [ -f /lib/systemd/system/avahi-daemon.service ] ; then
    systemctl reload avahi-daemon 3>/dev/null || true
fi

mkdir -p /var/cache/vendorzone/ 
chown $WEBUSER:$WEBUSER -R /var/cache/vendorzone/ 

mkdir -p /var/lib/vendorzone/tmp
chown $WEBUSER:$WEBUSER /var/lib/vendorzone/ -R

mkdir -p /usr/share/vendorzone
chown $WEBUSER:$WEBUSER /usr/share/vendorzone/ -R
cd /usr/share/vendorzone
if [ -f composer.lock ] ; then
    rm -f composer.lock
fi
mkdir -p /var/lib/composer
chown $WEBUSER:$WEBUSER /var/lib/composer
su - $WEBUSER -s /bin/bash -c 'COMPOSER_HOME="/var/lib/composer" composer --no-dev -o install -d /usr/share/vendorzone/'

db_get "vendorzone/DB_TYPE"
replaceYML "adapter" $RET
db_get "vendorzone/DB_HOST"
replaceYML "host" $RET
db_get "vendorzone/DB_PORT"
replaceYML "port" $RET
db_get "vendorzone/DB_USERNAME"
replaceYML "user" $RET
db_get "vendorzone/DB_PASSWORD"
replaceYML "pass" $RET
db_get "vendorzone/DB_DATABASE"
replaceYML "name" $RET

phinx -n -c/var/lib/vendorzone/phinx.yml migrate



exit 0
